# NOTE: This was built with
# `gutenberg 0.3.3`

# The URL the site will be built for
base_url = "https://glitzflitz.github.io"

title = "Amey's Midnight Musings"
description = "Incredibly niche and unrelatable content"

compile_sass = true

[markdown]
highlight_code = true

build_search_index = true

theme = "hyde"

generate_rss = true

[extra]
# Put all your custom variables here
hyde_links = [
]
hyde_theme = "theme-base-1f"
